### ISSUE TITLE
aanmelden voor administrators

### ISSUE THREAD

**Issue by bampe** [bertBruynooghe/type_one_too#3]
administrators zouden moeten toegang hebben tot de templates voor de mails, de mogelijkheid om adressen te wissen (indien niet meer lid) en de mogelijkheid om mails toe te voegen om eenmalig te versturen (zoals bv reclame gezinsweekend, vakanties enz

**Comment by bertBruynooghe** [comment]
gebruiker zal rol krijgen, en voor het moment dacht ik aan 3 rollen: gebruiker, copywriter en admin.
Copywriter kan nieuwe emails aanmaken, maar niet bepalen wanneer er moet verstuurd worden.

**Comment by bertBruynooghe** [comment]
Users hebben nu een role attribute. Als dat op 'admin' staat kunnen ze aan de /users pagina, anders krijg je daar een error op. Huidige users zijn nu admin users, en kunnen users die zelf inschrijven admin maken.

**Comment by bertBruynooghe** [comment]
Rest van functionaliteit volgt later
